/*
 * Project name:
     Calculator.vtft
 * Generated by:
     Visual TFT
 * Date of creation
     12/20/2011
 * Time of creation
     12:09:05 PM
 * Test configuration:
     MCU:             P18F87J50
     Dev.Board:       MikroMMB_for_PIC18FJ_hw_rev_1.10
                      http://www.mikroe.com/mikromedia/pic18fj/
     Oscillator:      48000000 Hz
     SW:              mikroC PRO for PIC
                      http://www.mikroe.com/mikroc/pic/
 */

#include "Calculator_objects.h"

void main() {

  Start_TP();

  while (1) {
    Check_TP();

  }

}
