/*
 * Project name:
     hello_world.vtft
 * Generated by:
     Visual TFT
 * Date of creation
     12/20/2011
 * Time of creation
     12:44:06 PM
 * Test configuration:
     MCU:             P18F87J50
     Dev.Board:       MikroMMB_for_PIC18FJ_hw_rev_1.10
                      http://www.mikroe.com/mikromedia/pic18fj/
     Oscillator:      48000000 Hz
     SW:              mikroC PRO for PIC
                      http://www.mikroe.com/mikroc/pic/
 */

#include "hello_world_objects.h"
void Start_screen(); extern;
void main() {

  Start_TP();
  Start_screen();

  while (1) {
    Check_TP();

  }

}